<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>D Continuous Random Variables in R | MATH 340 Notes</title>
  <meta name="description" content="D Continuous Random Variables in R | MATH 340 Notes" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="D Continuous Random Variables in R | MATH 340 Notes" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="D Continuous Random Variables in R | MATH 340 Notes" />
  
  
  

<meta name="author" content="Mike Hitchman" />


<meta name="date" content="2024-07-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="R-discreteRV.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Math 340 Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="sets.html"><a href="sets.html"><i class="fa fa-check"></i><b>2</b> Sets</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sets.html"><a href="sets.html#algebra-of-sets"><i class="fa fa-check"></i><b>2.1</b> Algebra of Sets</a></li>
<li class="chapter" data-level="2.2" data-path="sets.html"><a href="sets.html#size-of-sets"><i class="fa fa-check"></i><b>2.2</b> Set sizes</a></li>
<li class="chapter" data-level="2.3" data-path="sets.html"><a href="sets.html#sets-in-r"><i class="fa fa-check"></i><b>2.3</b> Sets in R</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="discrete-probability-distributions.html"><a href="discrete-probability-distributions.html"><i class="fa fa-check"></i><b>3</b> Discrete Probability Distributions</a>
<ul>
<li class="chapter" data-level="3.1" data-path="discrete-probability-distributions.html"><a href="discrete-probability-distributions.html#sample-space"><i class="fa fa-check"></i><b>3.1</b> Sample Space</a></li>
<li class="chapter" data-level="3.2" data-path="discrete-probability-distributions.html"><a href="discrete-probability-distributions.html#discrete-random-variables"><i class="fa fa-check"></i><b>3.2</b> Discrete Random Variables</a></li>
<li class="chapter" data-level="3.3" data-path="discrete-probability-distributions.html"><a href="discrete-probability-distributions.html#calculating-probabilities"><i class="fa fa-check"></i><b>3.3</b> Calculating Probabilities</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="discrete-probability-distributions.html"><a href="discrete-probability-distributions.html#sample-point-method"><i class="fa fa-check"></i><b>3.3.1</b> Sample Point Method</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="counting.html"><a href="counting.html"><i class="fa fa-check"></i><b>4</b> Counting Techniques</a>
<ul>
<li class="chapter" data-level="4.1" data-path="counting.html"><a href="counting.html#multipiclation-principle"><i class="fa fa-check"></i><b>4.1</b> Multipiclation Principle</a></li>
<li class="chapter" data-level="4.2" data-path="counting.html"><a href="counting.html#permutations"><i class="fa fa-check"></i><b>4.2</b> Permutations</a></li>
<li class="chapter" data-level="4.3" data-path="counting.html"><a href="counting.html#combinations"><i class="fa fa-check"></i><b>4.3</b> Combinations</a></li>
<li class="chapter" data-level="4.4" data-path="counting.html"><a href="counting.html#multinomial-coefficients"><i class="fa fa-check"></i><b>4.4</b> Multinomial Coefficients</a></li>
<li class="chapter" data-level="4.5" data-path="counting.html"><a href="counting.html#balls-and-bins"><i class="fa fa-check"></i><b>4.5</b> Balls and Bins</a></li>
<li class="chapter" data-level="4.6" data-path="counting.html"><a href="counting.html#prob-with-counting-tools"><i class="fa fa-check"></i><b>4.6</b> Calculating More Probabilities</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="probability-theory.html"><a href="probability-theory.html"><i class="fa fa-check"></i><b>5</b> Probability Theory</a>
<ul>
<li class="chapter" data-level="5.1" data-path="probability-theory.html"><a href="probability-theory.html#conditional-probability-and-independence"><i class="fa fa-check"></i><b>5.1</b> Conditional Probability and Independence</a></li>
<li class="chapter" data-level="5.2" data-path="probability-theory.html"><a href="probability-theory.html#two-laws-of-probability"><i class="fa fa-check"></i><b>5.2</b> Two Laws of Probability</a></li>
<li class="chapter" data-level="5.3" data-path="probability-theory.html"><a href="probability-theory.html#event-composition-method"><i class="fa fa-check"></i><b>5.3</b> Event-Composition Method</a></li>
<li class="chapter" data-level="5.4" data-path="probability-theory.html"><a href="probability-theory.html#bayes-rule"><i class="fa fa-check"></i><b>5.4</b> Bayes’ Rule</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="discrete-random-variables-1.html"><a href="discrete-random-variables-1.html"><i class="fa fa-check"></i><b>6</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="6.1" data-path="discrete-random-variables-1.html"><a href="discrete-random-variables-1.html#expected-value"><i class="fa fa-check"></i><b>6.1</b> Expected Value</a></li>
<li class="chapter" data-level="6.2" data-path="discrete-random-variables-1.html"><a href="discrete-random-variables-1.html#variance"><i class="fa fa-check"></i><b>6.2</b> Variance</a></li>
<li class="chapter" data-level="6.3" data-path="discrete-random-variables-1.html"><a href="discrete-random-variables-1.html#properties-of-expected-value"><i class="fa fa-check"></i><b>6.3</b> Properties of Expected Value</a></li>
<li class="chapter" data-level="6.4" data-path="discrete-random-variables-1.html"><a href="discrete-random-variables-1.html#tchebysheffs-theorem"><i class="fa fa-check"></i><b>6.4</b> Tchebysheff’s Theorem</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="important-discrete-rv.html"><a href="important-discrete-rv.html"><i class="fa fa-check"></i><b>7</b> Important Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="7.1" data-path="important-discrete-rv.html"><a href="important-discrete-rv.html#binomial"><i class="fa fa-check"></i><b>7.1</b> Binomial Distributions</a></li>
<li class="chapter" data-level="7.2" data-path="important-discrete-rv.html"><a href="important-discrete-rv.html#geometric"><i class="fa fa-check"></i><b>7.2</b> Geometric Distributions</a></li>
<li class="chapter" data-level="7.3" data-path="important-discrete-rv.html"><a href="important-discrete-rv.html#negative-binomial"><i class="fa fa-check"></i><b>7.3</b> Negative Binomial Distribution</a></li>
<li class="chapter" data-level="7.4" data-path="important-discrete-rv.html"><a href="important-discrete-rv.html#hypergometric"><i class="fa fa-check"></i><b>7.4</b> Hypergeometric Distribution</a></li>
<li class="chapter" data-level="7.5" data-path="important-discrete-rv.html"><a href="important-discrete-rv.html#poisson"><i class="fa fa-check"></i><b>7.5</b> Poisson Distribution</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="important-discrete-rv.html"><a href="important-discrete-rv.html#poisson-process"><i class="fa fa-check"></i><b>7.5.1</b> Poisson Process</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="moments-and-moment-generating-functions.html"><a href="moments-and-moment-generating-functions.html"><i class="fa fa-check"></i><b>8</b> Moments and Moment-Generating Functions</a></li>
<li class="chapter" data-level="9" data-path="continuous-rv.html"><a href="continuous-rv.html"><i class="fa fa-check"></i><b>9</b> Continuous Random Variables</a>
<ul>
<li class="chapter" data-level="9.1" data-path="continuous-rv.html"><a href="continuous-rv.html#distribution-functions"><i class="fa fa-check"></i><b>9.1</b> Distribution Functions</a></li>
<li class="chapter" data-level="9.2" data-path="continuous-rv.html"><a href="continuous-rv.html#expected-value-for-continuous-random-variables"><i class="fa fa-check"></i><b>9.2</b> Expected Value for Continuous Random Variables</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="important-continuous-rv.html"><a href="important-continuous-rv.html"><i class="fa fa-check"></i><b>10</b> Important Continuous Random Variables</a>
<ul>
<li class="chapter" data-level="10.1" data-path="important-continuous-rv.html"><a href="important-continuous-rv.html#uniform-continuous"><i class="fa fa-check"></i><b>10.1</b> Uniform Distribution</a></li>
<li class="chapter" data-level="10.2" data-path="important-continuous-rv.html"><a href="important-continuous-rv.html#exponential-distribution"><i class="fa fa-check"></i><b>10.2</b> Exponential Distribution</a></li>
<li class="chapter" data-level="10.3" data-path="important-continuous-rv.html"><a href="important-continuous-rv.html#normal"><i class="fa fa-check"></i><b>10.3</b> Normal Distribution</a></li>
<li class="chapter" data-level="10.4" data-path="important-continuous-rv.html"><a href="important-continuous-rv.html#gamma-distribution"><i class="fa fa-check"></i><b>10.4</b> Gamma Distribution</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="important-continuous-rv.html"><a href="important-continuous-rv.html#exponential-distribution-1"><i class="fa fa-check"></i><b>10.4.1</b> Exponential Distribution</a></li>
<li class="chapter" data-level="10.4.2" data-path="important-continuous-rv.html"><a href="important-continuous-rv.html#chi-square-distribution"><i class="fa fa-check"></i><b>10.4.2</b> Chi-square distribution</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="important-continuous-rv.html"><a href="important-continuous-rv.html#beta-distribution"><i class="fa fa-check"></i><b>10.5</b> Beta Distribution</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="mgf.html"><a href="mgf.html"><i class="fa fa-check"></i><b>11</b> Moment Generating Functions</a></li>
<li class="chapter" data-level="12" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html"><i class="fa fa-check"></i><b>12</b> Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="12.1" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#sums-of-random-variables"><i class="fa fa-check"></i><b>12.1</b> Sums of Random Variables</a></li>
<li class="chapter" data-level="12.2" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#t-distribution"><i class="fa fa-check"></i><b>12.2</b> T distribution</a></li>
<li class="chapter" data-level="12.3" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>12.3</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="12.4" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#normal-approximation-to-a-binomial-distribution"><i class="fa fa-check"></i><b>12.4</b> Normal Approximation to a binomial distribution</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="estimation.html"><a href="estimation.html"><i class="fa fa-check"></i><b>13</b> Estimation</a>
<ul>
<li class="chapter" data-level="13.1" data-path="estimation.html"><a href="estimation.html#unbiased-estimators"><i class="fa fa-check"></i><b>13.1</b> Unbiased Estimators</a></li>
<li class="chapter" data-level="13.2" data-path="estimation.html"><a href="estimation.html#order-statistics"><i class="fa fa-check"></i><b>13.2</b> Order Statistics</a></li>
<li class="chapter" data-level="13.3" data-path="estimation.html"><a href="estimation.html#common-unbiased-estimators"><i class="fa fa-check"></i><b>13.3</b> Common Unbiased Estimators</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="estimation.html"><a href="estimation.html#estimating-mu-a-population-mean"><i class="fa fa-check"></i><b>13.3.1</b> Estimating <span class="math inline">\(\mu\)</span>, a population mean</a></li>
<li class="chapter" data-level="13.3.2" data-path="estimation.html"><a href="estimation.html#estimating-p-a-population-proportion"><i class="fa fa-check"></i><b>13.3.2</b> Estimating <span class="math inline">\(p\)</span>, a population proportion</a></li>
<li class="chapter" data-level="13.3.3" data-path="estimation.html"><a href="estimation.html#estimating-mu_1---mu_2-the-difference-of-two-population-means"><i class="fa fa-check"></i><b>13.3.3</b> Estimating <span class="math inline">\(\mu_1 - \mu_2\)</span>, the difference of two population means</a></li>
<li class="chapter" data-level="13.3.4" data-path="estimation.html"><a href="estimation.html#estimating-p_1---p_2-the-difference-of-two-population-proportions"><i class="fa fa-check"></i><b>13.3.4</b> Estimating <span class="math inline">\(p_1 - p_2\)</span>, the difference of two population proportions</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Using R</b></span></li>
<li class="chapter" data-level="A" data-path="sampling-in-r.html"><a href="sampling-in-r.html"><i class="fa fa-check"></i><b>A</b> Sampling in R</a>
<ul>
<li class="chapter" data-level="A.1" data-path="sampling-in-r.html"><a href="sampling-in-r.html#vectors-R"><i class="fa fa-check"></i><b>A.1</b> Data vectors</a>
<ul>
<li class="chapter" data-level="A.1.1" data-path="sampling-in-r.html"><a href="sampling-in-r.html#vector-types"><i class="fa fa-check"></i><b>A.1.1</b> vector types</a></li>
<li class="chapter" data-level="A.1.2" data-path="sampling-in-r.html"><a href="sampling-in-r.html#matrices"><i class="fa fa-check"></i><b>A.1.2</b> Matrices</a></li>
<li class="chapter" data-level="A.1.3" data-path="sampling-in-r.html"><a href="sampling-in-r.html#data-frames"><i class="fa fa-check"></i><b>A.1.3</b> data frames</a></li>
<li class="chapter" data-level="A.1.4" data-path="sampling-in-r.html"><a href="sampling-in-r.html#common-vector-commands"><i class="fa fa-check"></i><b>A.1.4</b> common vector commands</a></li>
<li class="chapter" data-level="A.1.5" data-path="sampling-in-r.html"><a href="sampling-in-r.html#comparison-operators"><i class="fa fa-check"></i><b>A.1.5</b> Comparison Operators</a></li>
<li class="chapter" data-level="A.1.6" data-path="sampling-in-r.html"><a href="sampling-in-r.html#sum-and-which"><i class="fa fa-check"></i><b>A.1.6</b> <code>sum()</code> and <code>which()</code></a></li>
<li class="chapter" data-level="A.1.7" data-path="sampling-in-r.html"><a href="sampling-in-r.html#extracting-elements"><i class="fa fa-check"></i><b>A.1.7</b> extracting elements</a></li>
<li class="chapter" data-level="A.1.8" data-path="sampling-in-r.html"><a href="sampling-in-r.html#comparing-vectors"><i class="fa fa-check"></i><b>A.1.8</b> comparing vectors</a></li>
<li class="chapter" data-level="A.1.9" data-path="sampling-in-r.html"><a href="sampling-in-r.html#vector-arithmetic"><i class="fa fa-check"></i><b>A.1.9</b> vector arithmetic</a></li>
<li class="chapter" data-level="A.1.10" data-path="sampling-in-r.html"><a href="sampling-in-r.html#concatenate-vectors"><i class="fa fa-check"></i><b>A.1.10</b> concatenate vectors</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="sampling-in-r.html"><a href="sampling-in-r.html#special-vectors"><i class="fa fa-check"></i><b>A.2</b> Special vectors</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="sampling-in-r.html"><a href="sampling-in-r.html#consecutive-integers"><i class="fa fa-check"></i><b>A.2.1</b> consecutive integers</a></li>
<li class="chapter" data-level="A.2.2" data-path="sampling-in-r.html"><a href="sampling-in-r.html#letters"><i class="fa fa-check"></i><b>A.2.2</b> letters</a></li>
<li class="chapter" data-level="A.2.3" data-path="sampling-in-r.html"><a href="sampling-in-r.html#rep"><i class="fa fa-check"></i><b>A.2.3</b> <code>rep()</code></a></li>
<li class="chapter" data-level="A.2.4" data-path="sampling-in-r.html"><a href="sampling-in-r.html#table"><i class="fa fa-check"></i><b>A.2.4</b> <code>table()</code></a></li>
<li class="chapter" data-level="A.2.5" data-path="sampling-in-r.html"><a href="sampling-in-r.html#seq"><i class="fa fa-check"></i><b>A.2.5</b> <code>seq()</code></a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="sampling-in-r.html"><a href="sampling-in-r.html#sampling-in-R"><i class="fa fa-check"></i><b>A.3</b> Sampling</a>
<ul>
<li class="chapter" data-level="A.3.1" data-path="sampling-in-r.html"><a href="sampling-in-r.html#sample-options"><i class="fa fa-check"></i><b>A.3.1</b> <code>sample()</code> options</a></li>
<li class="chapter" data-level="A.3.2" data-path="sampling-in-r.html"><a href="sampling-in-r.html#sample-without-replacement"><i class="fa fa-check"></i><b>A.3.2</b> Sample without replacement</a></li>
<li class="chapter" data-level="A.3.3" data-path="sampling-in-r.html"><a href="sampling-in-r.html#sample-with-replacement"><i class="fa fa-check"></i><b>A.3.3</b> Sample with replacement</a></li>
<li class="chapter" data-level="A.3.4" data-path="sampling-in-r.html"><a href="sampling-in-r.html#sample-with-custom-probabilities"><i class="fa fa-check"></i><b>A.3.4</b> Sample with custom probabilities</a></li>
<li class="chapter" data-level="A.3.5" data-path="sampling-in-r.html"><a href="sampling-in-r.html#example-lefties"><i class="fa fa-check"></i><b>A.3.5</b> Example: Lefties</a></li>
</ul></li>
<li class="chapter" data-level="A.4" data-path="sampling-in-r.html"><a href="sampling-in-r.html#repeated-sampling"><i class="fa fa-check"></i><b>A.4</b> Repeated Sampling</a>
<ul>
<li class="chapter" data-level="A.4.1" data-path="sampling-in-r.html"><a href="sampling-in-r.html#using-a-for-loop"><i class="fa fa-check"></i><b>A.4.1</b> using a <code>for</code> loop</a></li>
<li class="chapter" data-level="A.4.2" data-path="sampling-in-r.html"><a href="sampling-in-r.html#using-replicate"><i class="fa fa-check"></i><b>A.4.2</b> using <code>replicate()</code></a></li>
</ul></li>
<li class="chapter" data-level="A.5" data-path="sampling-in-r.html"><a href="sampling-in-r.html#sampling-commands"><i class="fa fa-check"></i><b>A.5</b> Summary of R commands</a>
<ul>
<li class="chapter" data-level="A.5.1" data-path="sampling-in-r.html"><a href="sampling-in-r.html#defining-vectors"><i class="fa fa-check"></i><b>A.5.1</b> defining vectors</a></li>
<li class="chapter" data-level="A.5.2" data-path="sampling-in-r.html"><a href="sampling-in-r.html#summarizing-vectors"><i class="fa fa-check"></i><b>A.5.2</b> summarizing vectors</a></li>
<li class="chapter" data-level="A.5.3" data-path="sampling-in-r.html"><a href="sampling-in-r.html#sampling-from-vectors"><i class="fa fa-check"></i><b>A.5.3</b> sampling from vectors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="R-sim-probability.html"><a href="R-sim-probability.html"><i class="fa fa-check"></i><b>B</b> Simulating Probability in R</a>
<ul>
<li class="chapter" data-level="B.1" data-path="R-sim-probability.html"><a href="R-sim-probability.html#id_10sided-die-R"><i class="fa fa-check"></i><b>B.1</b> Rolling a 10-sided die</a>
<ul>
<li class="chapter" data-level="B.1.1" data-path="R-sim-probability.html"><a href="R-sim-probability.html#final-code"><i class="fa fa-check"></i><b>B.1.1</b> Final Code</a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="R-sim-probability.html"><a href="R-sim-probability.html#diff-2dice-R"><i class="fa fa-check"></i><b>B.2</b> Difference of two dice</a></li>
<li class="chapter" data-level="B.3" data-path="R-sim-probability.html"><a href="R-sim-probability.html#flip-coin-R"><i class="fa fa-check"></i><b>B.3</b> Flipping a coin</a></li>
<li class="chapter" data-level="B.4" data-path="R-sim-probability.html"><a href="R-sim-probability.html#marbles-urn-R"><i class="fa fa-check"></i><b>B.4</b> Marbles from an urn</a></li>
<li class="chapter" data-level="B.5" data-path="R-sim-probability.html"><a href="R-sim-probability.html#partition-set-R"><i class="fa fa-check"></i><b>B.5</b> Splitting a set into multiple subsets</a>
<ul>
<li class="chapter" data-level="B.5.1" data-path="R-sim-probability.html"><a href="R-sim-probability.html#final-code-1"><i class="fa fa-check"></i><b>B.5.1</b> Final Code</a></li>
</ul></li>
<li class="chapter" data-level="B.6" data-path="R-sim-probability.html"><a href="R-sim-probability.html#license-plates-R"><i class="fa fa-check"></i><b>B.6</b> Oregon License Plates</a>
<ul>
<li class="chapter" data-level="B.6.1" data-path="R-sim-probability.html"><a href="R-sim-probability.html#final-code-2"><i class="fa fa-check"></i><b>B.6.1</b> Final Code</a></li>
</ul></li>
<li class="chapter" data-level="B.7" data-path="R-sim-probability.html"><a href="R-sim-probability.html#pollsters-R"><i class="fa fa-check"></i><b>B.7</b> Pollsters</a></li>
<li class="chapter" data-level="B.8" data-path="R-sim-probability.html"><a href="R-sim-probability.html#same-birthday-R"><i class="fa fa-check"></i><b>B.8</b> Matching Birthdays</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="R-discreteRV.html"><a href="R-discreteRV.html"><i class="fa fa-check"></i><b>C</b> Discrete Random Variables in R</a>
<ul>
<li class="chapter" data-level="C.1" data-path="R-discreteRV.html"><a href="R-discreteRV.html#expected-value-of-x"><i class="fa fa-check"></i><b>C.1</b> Expected Value of <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="C.2" data-path="R-discreteRV.html"><a href="R-discreteRV.html#variance-of-x"><i class="fa fa-check"></i><b>C.2</b> Variance of <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="C.3" data-path="R-discreteRV.html"><a href="R-discreteRV.html#distribution-plots"><i class="fa fa-check"></i><b>C.3</b> Distribution Plots</a></li>
<li class="chapter" data-level="C.4" data-path="R-discreteRV.html"><a href="R-discreteRV.html#sampling"><i class="fa fa-check"></i><b>C.4</b> Sampling</a></li>
<li class="chapter" data-level="C.5" data-path="R-discreteRV.html"><a href="R-discreteRV.html#estimating-distributions-via-simulation"><i class="fa fa-check"></i><b>C.5</b> Estimating Distributions via Simulation</a></li>
<li class="chapter" data-level="C.6" data-path="R-discreteRV.html"><a href="R-discreteRV.html#discrete-uniform-distribution"><i class="fa fa-check"></i><b>C.6</b> Discrete Uniform Distribution</a></li>
<li class="chapter" data-level="C.7" data-path="R-discreteRV.html"><a href="R-discreteRV.html#r-4distn-functions"><i class="fa fa-check"></i><b>C.7</b> Important discrete random variables</a>
<ul>
<li class="chapter" data-level="C.7.1" data-path="R-discreteRV.html"><a href="R-discreteRV.html#binomial-distribution-binom"><i class="fa fa-check"></i><b>C.7.1</b> Binomial Distribution <code>binom</code></a></li>
<li class="chapter" data-level="C.7.2" data-path="R-discreteRV.html"><a href="R-discreteRV.html#geometric-distribution-geom"><i class="fa fa-check"></i><b>C.7.2</b> Geometric Distribution <code>geom</code></a></li>
<li class="chapter" data-level="C.7.3" data-path="R-discreteRV.html"><a href="R-discreteRV.html#negative-binomial-distribution-nbinom"><i class="fa fa-check"></i><b>C.7.3</b> Negative Binomial Distribution <code>nbinom</code></a></li>
<li class="chapter" data-level="C.7.4" data-path="R-discreteRV.html"><a href="R-discreteRV.html#hypergeometric-distribution-hyper"><i class="fa fa-check"></i><b>C.7.4</b> Hypergeometric Distribution <code>hyper</code></a></li>
<li class="chapter" data-level="C.7.5" data-path="R-discreteRV.html"><a href="R-discreteRV.html#poisson-distribution-pois"><i class="fa fa-check"></i><b>C.7.5</b> Poisson Distribution <code>pois</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="D" data-path="R-continuousRV.html"><a href="R-continuousRV.html"><i class="fa fa-check"></i><b>D</b> Continuous Random Variables in R</a>
<ul>
<li class="chapter" data-level="D.1" data-path="R-continuousRV.html"><a href="R-continuousRV.html#unifR"><i class="fa fa-check"></i><b>D.1</b> Uniform Distribution</a>
<ul>
<li class="chapter" data-level="D.1.1" data-path="R-continuousRV.html"><a href="R-continuousRV.html#picking-random-numbers"><i class="fa fa-check"></i><b>D.1.1</b> Picking random numbers!</a></li>
<li class="chapter" data-level="D.1.2" data-path="R-continuousRV.html"><a href="R-continuousRV.html#picking-random-points-in-the-unit-square"><i class="fa fa-check"></i><b>D.1.2</b> Picking random points in the unit square!</a></li>
<li class="chapter" data-level="D.1.3" data-path="R-continuousRV.html"><a href="R-continuousRV.html#estimate-the-value-of-pi"><i class="fa fa-check"></i><b>D.1.3</b> Estimate the value of <span class="math inline">\(\pi\)</span></a></li>
</ul></li>
<li class="chapter" data-level="D.2" data-path="R-continuousRV.html"><a href="R-continuousRV.html#normalR"><i class="fa fa-check"></i><b>D.2</b> Normal Distribution <code>norm</code></a>
<ul>
<li class="chapter" data-level="D.2.1" data-path="R-continuousRV.html"><a href="R-continuousRV.html#sampling-distribution-of-a-sample-mean"><i class="fa fa-check"></i><b>D.2.1</b> Sampling Distribution of a sample mean</a></li>
</ul></li>
<li class="chapter" data-level="D.3" data-path="R-continuousRV.html"><a href="R-continuousRV.html#expR"><i class="fa fa-check"></i><b>D.3</b> Exponential Distribution <code>exp</code></a></li>
<li class="chapter" data-level="D.4" data-path="R-continuousRV.html"><a href="R-continuousRV.html#gammaR"><i class="fa fa-check"></i><b>D.4</b> Gamma Distribution <code>gamma</code></a></li>
<li class="chapter" data-level="D.5" data-path="R-continuousRV.html"><a href="R-continuousRV.html#chiR"><i class="fa fa-check"></i><b>D.5</b> Chi-square Distribution <code>chisq</code></a></li>
<li class="chapter" data-level="D.6" data-path="R-continuousRV.html"><a href="R-continuousRV.html#betaR"><i class="fa fa-check"></i><b>D.6</b> Beta distribution <code>beta</code></a></li>
<li class="chapter" data-level="D.7" data-path="R-continuousRV.html"><a href="R-continuousRV.html#customR"><i class="fa fa-check"></i><b>D.7</b> Homemade Continuous Random Variables</a>
<ul>
<li class="chapter" data-level="D.7.1" data-path="R-continuousRV.html"><a href="R-continuousRV.html#input-the-density-function"><i class="fa fa-check"></i><b>D.7.1</b> Input the density function</a></li>
<li class="chapter" data-level="D.7.2" data-path="R-continuousRV.html"><a href="R-continuousRV.html#visualize-the-density-function"><i class="fa fa-check"></i><b>D.7.2</b> Visualize the density function</a></li>
<li class="chapter" data-level="D.7.3" data-path="R-continuousRV.html"><a href="R-continuousRV.html#estimating-integrals-with-riemann-sums"><i class="fa fa-check"></i><b>D.7.3</b> Estimating Integrals with Riemann Sums</a></li>
<li class="chapter" data-level="D.7.4" data-path="R-continuousRV.html"><a href="R-continuousRV.html#estimating-probabilities"><i class="fa fa-check"></i><b>D.7.4</b> Estimating Probabilities</a></li>
<li class="chapter" data-level="D.7.5" data-path="R-continuousRV.html"><a href="R-continuousRV.html#the-distribution-function-fx"><i class="fa fa-check"></i><b>D.7.5</b> The distribution function <span class="math inline">\(F(X)\)</span></a></li>
<li class="chapter" data-level="D.7.6" data-path="R-continuousRV.html"><a href="R-continuousRV.html#estimating-moments"><i class="fa fa-check"></i><b>D.7.6</b> Estimating Moments</a></li>
<li class="chapter" data-level="D.7.7" data-path="R-continuousRV.html"><a href="R-continuousRV.html#expected-value-1"><i class="fa fa-check"></i><b>D.7.7</b> Expected Value</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MATH 340 Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="R-continuousRV" class="section level1 hasAnchor" number="17">
<h1><span class="header-section-number">D</span> Continuous Random Variables in R<a href="R-continuousRV.html#R-continuousRV" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Here we investigate in R the common, named continuous random variables we encounter in MATH 340:</p>
<ul>
<li><a href="R-continuousRV.html#unifR">Uniform probability distribution</a> | <code>unif</code></li>
<li><a href="R-continuousRV.html#normalR">Normal probability distribution</a> | <code>norm</code></li>
<li><a href="R-continuousRV.html#gammaR">Gamma probability distribution</a> | <code>gamma</code></li>
<li><a href="R-continuousRV.html#expR">Exponential probability distribution</a> | <code>exp</code></li>
<li><a href="R-continuousRV.html#chiR">Chi-square probability distribution</a> | <code>chisq</code></li>
<li><a href="R-continuousRV.html#betaR">Beta probability distribution</a> | <code>beta</code></li>
</ul>
<p>For each of these distributions we may use the 4 associated commands:</p>
<ul>
<li><code>d___()</code> gives the density function</li>
<li><code>p___()</code> gives cumulative probability</li>
<li><code>q___()</code> gives quantiles</li>
<li><code>r___()</code> gives random samples</li>
</ul>
<p>We also discuss below how to build and analyze <a href="R-continuousRV.html#customR">homemade continuous random variables in R</a>.</p>
<div id="unifR" class="section level2 hasAnchor" number="17.1">
<h2><span class="header-section-number">D.1</span> Uniform Distribution<a href="R-continuousRV.html#unifR" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The uniform distribution is so very useful, it deserves top-billing here. With it we can generate random numbers, and from it we can build other interesting distributions.</p>
<p>A uniform random variable <span class="math inline">\(X\)</span> over the interval <span class="math inline">\([a,b]\)</span> has density function <span class="math display">\[f(x) = \frac{1}{b-a}, ~~\text{ for all }~~ a \leq x \leq b.\]</span></p>
<div id="picking-random-numbers" class="section level3 hasAnchor" number="17.1.1">
<h3><span class="header-section-number">D.1.1</span> Picking random numbers!<a href="R-continuousRV.html#picking-random-numbers" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="R-continuousRV.html#cb251-1" tabindex="-1"></a><span class="fu">runif</span>(<span class="dv">10</span>,<span class="dv">0</span>,<span class="dv">1</span>) <span class="co">#pick 10 random numbers between 0 and 1.</span></span></code></pre></div>
<pre><code>##  [1] 0.86321882 0.37507535 0.79892100 0.74604511 0.08882514 0.13399653
##  [7] 0.64399745 0.14468099 0.33706760 0.66699855</code></pre>
</div>
<div id="picking-random-points-in-the-unit-square" class="section level3 hasAnchor" number="17.1.2">
<h3><span class="header-section-number">D.1.2</span> Picking random points in the unit square!<a href="R-continuousRV.html#picking-random-points-in-the-unit-square" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="R-continuousRV.html#cb253-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">runif</span>(<span class="dv">100</span>,<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb253-2"><a href="R-continuousRV.html#cb253-2" tabindex="-1"></a>                 <span class="at">y=</span><span class="fu">runif</span>(<span class="dv">100</span>,<span class="dv">0</span>,<span class="dv">1</span>)))<span class="sc">+</span></span>
<span id="cb253-3"><a href="R-continuousRV.html#cb253-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(x,y),<span class="at">col=</span><span class="st">&quot;steelblue&quot;</span>)<span class="sc">+</span></span>
<span id="cb253-4"><a href="R-continuousRV.html#cb253-4" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-172-1.png" width="288" /></p>
</div>
<div id="estimate-the-value-of-pi" class="section level3 hasAnchor" number="17.1.3">
<h3><span class="header-section-number">D.1.3</span> Estimate the value of <span class="math inline">\(\pi\)</span><a href="R-continuousRV.html#estimate-the-value-of-pi" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="R-continuousRV.html#cb254-1" tabindex="-1"></a>points<span class="ot">=</span><span class="dv">5000</span></span>
<span id="cb254-2"><a href="R-continuousRV.html#cb254-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">runif</span>(points,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb254-3"><a href="R-continuousRV.html#cb254-3" tabindex="-1"></a>                 <span class="at">y=</span><span class="fu">runif</span>(points,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb254-4"><a href="R-continuousRV.html#cb254-4" tabindex="-1"></a>df<span class="sc">$</span>circle <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">sqrt</span>(df<span class="sc">$</span>x<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span>df<span class="sc">$</span>y<span class="sc">^</span><span class="dv">2</span>)<span class="sc">&lt;</span><span class="dv">1</span>,<span class="st">&quot;yes&quot;</span>,<span class="st">&quot;no&quot;</span>)</span>
<span id="cb254-5"><a href="R-continuousRV.html#cb254-5" tabindex="-1"></a><span class="fu">ggplot</span>(df)<span class="sc">+</span></span>
<span id="cb254-6"><a href="R-continuousRV.html#cb254-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(x,y,<span class="at">col=</span>circle),<span class="at">size=</span>.<span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb254-7"><a href="R-continuousRV.html#cb254-7" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.1</span>,<span class="fl">1.1</span>))<span class="sc">+</span><span class="fu">ylim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.1</span>,<span class="fl">1.1</span>))<span class="sc">+</span></span>
<span id="cb254-8"><a href="R-continuousRV.html#cb254-8" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-173-1.png" width="384" /></p>
<p>The area of the square is 2*2 = 4.
The area of the circle is <span class="math inline">\(\pi (1)^2 = \pi.\)</span> So the ratio<br />
<span class="math display">\[\text{(area of circle)/(area of square)}=\pi/4,\]</span>
and we can estimate <span class="math inline">\(\pi\)</span> as follows:
<span class="math display">\[\pi \approx 4\cdot \frac{\text{points in circle}}{\text{total points}}\]</span></p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="R-continuousRV.html#cb255-1" tabindex="-1"></a><span class="dv">4</span><span class="sc">*</span><span class="fu">sum</span>(df<span class="sc">$</span>circle<span class="sc">==</span><span class="st">&quot;yes&quot;</span>)<span class="sc">/</span>points <span class="co"># our estimate of pi</span></span></code></pre></div>
<pre><code>## [1] 3.1384</code></pre>
</div>
</div>
<div id="normalR" class="section level2 hasAnchor" number="17.2">
<h2><span class="header-section-number">D.2</span> Normal Distribution <code>norm</code><a href="R-continuousRV.html#normalR" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Thanks to the Central Limit Theorem this distribution has a central role in statistics.</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="R-continuousRV.html#cb257-1" tabindex="-1"></a>mu<span class="ot">=</span><span class="dv">10</span>; sigma<span class="ot">=</span><span class="dv">3</span></span>
<span id="cb257-2"><a href="R-continuousRV.html#cb257-2" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">seq</span>(mu<span class="dv">-4</span><span class="sc">*</span>sigma,mu<span class="sc">+</span><span class="dv">4</span><span class="sc">*</span>sigma,<span class="at">by=</span>.<span class="dv">01</span>)</span>
<span id="cb257-3"><a href="R-continuousRV.html#cb257-3" tabindex="-1"></a><span class="fu">plot</span>(x,<span class="fu">dnorm</span>(x,mu,sigma),<span class="at">type=</span><span class="st">&quot;l&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;f(x)&quot;</span>)</span></code></pre></div>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-175-1.png" width="672" /></p>
<blockquote>
<p><strong>Example</strong>: Suppose newborn birthweights are normally distributed with mean 7.8 pounds and standard deviation 0.95 pounds.<br />
a) What proportion of newborns weight more than 10 pounds?<br />
b) Find the birth weight that marks the bottom 1% of all birthweights.</p>
</blockquote>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="R-continuousRV.html#cb258-1" tabindex="-1"></a><span class="co"># part (a)</span></span>
<span id="cb258-2"><a href="R-continuousRV.html#cb258-2" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(<span class="dv">10</span>,<span class="at">mean=</span><span class="fl">7.8</span>,<span class="at">sd=</span><span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## [1] 0.01028488</code></pre>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="R-continuousRV.html#cb260-1" tabindex="-1"></a><span class="co"># part (b)</span></span>
<span id="cb260-2"><a href="R-continuousRV.html#cb260-2" tabindex="-1"></a><span class="fu">qnorm</span>(.<span class="dv">01</span>,<span class="at">mean=</span><span class="fl">7.8</span>, <span class="at">sd=</span><span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## [1] 5.58997</code></pre>
<div id="sampling-distribution-of-a-sample-mean" class="section level3 hasAnchor" number="17.2.1">
<h3><span class="header-section-number">D.2.1</span> Sampling Distribution of a sample mean<a href="R-continuousRV.html#sampling-distribution-of-a-sample-mean" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose we have a population of 5000 random numbers between 10 and 20, which should have a uniform looking frequency distribution:</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="R-continuousRV.html#cb262-1" tabindex="-1"></a>pop<span class="ot">=</span><span class="fu">runif</span>(<span class="dv">5000</span>,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb262-2"><a href="R-continuousRV.html#cb262-2" tabindex="-1"></a><span class="fu">hist</span>(pop,<span class="at">breaks=</span><span class="dv">15</span>, <span class="at">main=</span><span class="st">&quot;Population Distribution&quot;</span>)</span></code></pre></div>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-177-1.png" width="672" />
Now suppose we draw a sample of size 50 from this population, and compute the sample mean of these 50 values:</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="R-continuousRV.html#cb263-1" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">sample</span>(pop,<span class="dv">50</span>))</span></code></pre></div>
<pre><code>## [1] 14.18544</code></pre>
<p>Now let’s do that game for 10000 trials, and look at the distribution of 10000 sample means:</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="R-continuousRV.html#cb265-1" tabindex="-1"></a>trials<span class="ot">=</span><span class="dv">10000</span></span>
<span id="cb265-2"><a href="R-continuousRV.html#cb265-2" tabindex="-1"></a>results<span class="ot">=</span><span class="fu">c</span>()</span>
<span id="cb265-3"><a href="R-continuousRV.html#cb265-3" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>trials){</span>
<span id="cb265-4"><a href="R-continuousRV.html#cb265-4" tabindex="-1"></a>  results<span class="ot">=</span><span class="fu">c</span>(results,<span class="fu">mean</span>(<span class="fu">sample</span>(pop,<span class="dv">50</span>)))</span>
<span id="cb265-5"><a href="R-continuousRV.html#cb265-5" tabindex="-1"></a>}</span>
<span id="cb265-6"><a href="R-continuousRV.html#cb265-6" tabindex="-1"></a><span class="fu">hist</span>(results, <span class="at">main=</span><span class="st">&quot;Histogram of sample means&quot;</span>)</span></code></pre></div>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-179-1.png" width="672" /></p>
<p>Look Normal?</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="R-continuousRV.html#cb266-1" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">seq</span>(<span class="dv">12</span>,<span class="dv">18</span>,<span class="at">by=</span>.<span class="dv">05</span>)</span>
<span id="cb266-2"><a href="R-continuousRV.html#cb266-2" tabindex="-1"></a><span class="fu">hist</span>(results, <span class="at">main=</span><span class="st">&quot;Histogram of sample means&quot;</span>,<span class="at">freq=</span><span class="cn">FALSE</span>,<span class="at">breaks=</span><span class="dv">30</span>)</span>
<span id="cb266-3"><a href="R-continuousRV.html#cb266-3" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x,<span class="dv">15</span>,<span class="dv">10</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">12</span>)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">50</span>)),<span class="at">add=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-180-1.png" width="672" /></p>
</div>
</div>
<div id="expR" class="section level2 hasAnchor" number="17.3">
<h2><span class="header-section-number">D.3</span> Exponential Distribution <code>exp</code><a href="R-continuousRV.html#expR" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>An exponential random variable <span class="math inline">\(X\)</span> with parameter <span class="math inline">\(\beta\)</span> has pdf <span class="math display">\[f(x) = \frac{1}{\beta}e^{-x/\beta} ~~\text{ for }~~ x &gt; 0\]</span></p>
<p>The <strong>mean</strong> of this distribution is <span class="math inline">\(E(X) = \beta\)</span> and the <strong>rate</strong> associated to this distribution is <span class="math inline">\(1/\beta\)</span>. <strong>In R</strong>, we specify the exponential parameter by entering the rate <span class="math inline">\(1/\beta\)</span>, not <span class="math inline">\(\beta\)</span> itself.</p>
<blockquote>
<p>Suppose <span class="math inline">\(X\)</span> is exp(<span class="math inline">\(b\)</span>).<br />
<strong>In R</strong>, <span class="math inline">\(P(X \leq q)\)</span> is given by <code>pexp(q,1/b)</code></p>
</blockquote>
<blockquote>
<p><strong>Example</strong>: The life of a lightbulb is exponentially distributed with mean 120 hours. What is the probability that it lasts more than 200 hours?</p>
</blockquote>
<p>Here <span class="math inline">\(X\)</span> is exponential with parameter <span class="math inline">\(\beta = 120\)</span>. The rate associated with this distribution is 1/120, so <span class="math inline">\(P(X &gt; 200)\)</span> can be computed with</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="R-continuousRV.html#cb267-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pexp</span>(<span class="dv">200</span>,<span class="at">rate=</span><span class="dv">1</span><span class="sc">/</span><span class="dv">120</span>)</span></code></pre></div>
<pre><code>## [1] 0.1888756</code></pre>
<p>As a reminder, this probability corresponds to the integral
<span class="math display">\[\int_{200}^\infty \frac{1}{120}e^{-x/120}~dx\]</span> which corresponds to the shaded area below</p>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-182-1.png" width="591.36" style="display: block; margin: auto;" /></p>
<blockquote>
<p><strong>Example</strong>: What proportion of lightbulbs last fewer than 5 hours?</p>
</blockquote>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="R-continuousRV.html#cb269-1" tabindex="-1"></a><span class="fu">pexp</span>(<span class="dv">5</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">120</span>)</span></code></pre></div>
<pre><code>## [1] 0.04081054</code></pre>
<blockquote>
<p><strong>Example</strong>: Find the 5th percentile for this distribution.</p>
</blockquote>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="R-continuousRV.html#cb271-1" tabindex="-1"></a><span class="fu">qexp</span>(.<span class="dv">05</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">120</span>)</span></code></pre></div>
<pre><code>## [1] 6.155195</code></pre>
<p>So, 5% of lightbulbs last less than 6.16 hours.</p>
<blockquote>
<p><strong>Example</strong>: Suppose <span class="math inline">\(X\)</span> is an exponential random variable with parameter <span class="math inline">\(\beta = 2\)</span>. Sketch the density function <span class="math inline">\(f(x)\)</span> as well as the distribution function <span class="math inline">\(F(x)\)</span>.</p>
</blockquote>
<p>The density function is <span class="math inline">\(f(x) = \frac{1}{2}e^{-x/2}\)</span> for <span class="math inline">\(x &gt; 0\)</span>, and we can sketch it by plotting an <span class="math inline">\(x\)</span> vector of many inputs between, say, 0 and 10, and the corresponding values of <code>dexp()</code>:</p>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-185-1.png" width="591.36" style="display: block; margin: auto;" /></p>
<p>The distribution function, which gives cumulative probability is found by plotting <code>pexp()</code>:</p>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-186-1.png" width="591.36" style="display: block; margin: auto;" /></p>
<!--
## A Memoryless distribution

Along with the geometric distribution, the exponential distribution is *memoryless*, in this sense: For any $t,s>0$, $$P(X > t + s~|~X > s) = P(X > t).$$

For the geometric distribution we can interpret the above as follows: the probability of waiting more than $t$ trials to see the first success is the same as waiting more than $t$ additional trials after not seeing a success in the first $s$ trials.  

For the "lifetime of a light-bulb interpretation" of the exponential distribution:  However long the light bulb has already lasted, the probability that the light-bulb lasts at least $t$ more hours is the same. The probability that the light-bulb lasts an additional $t$ hours after already lasting $s$ hours is the same as the probability that the light-bulb lasts more than $t$ hours right out of the box.

We can estimate both $P(X>t)$ and $P(X>t+s ~|~ X>s)$ by checking a large random sample from an exponential distribution.


``` r
trials=10000
x=rexp(trials,rate=1/5)
s=2; t=3
p1=sum(x > t)/trials #P(X > t)
p2=sum(x[which(x > s)]>s+t)/sum(x>s) #P(X>t+s | X > s)
print(paste("Estimate for P(X>t):",round(p1,3)))
```

```
## [1] "Estimate for P(X>t): 0.544"
```

``` r
print(paste("Estimate for P(X>t+s | X>s):",round(p2,3)))
```

```
## [1] "Estimate for P(X>t+s | X>s): 0.551"
```
-->
</div>
<div id="gammaR" class="section level2 hasAnchor" number="17.4">
<h2><span class="header-section-number">D.4</span> Gamma Distribution <code>gamma</code><a href="R-continuousRV.html#gammaR" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Some random variables are always nonnegative, and yield distributions of data that are skewed right, as pictured below.
<img src="math340-notes_files/figure-html/unnamed-chunk-188-1.png" width="384" /></p>
<p>Some typically skewed right distributions include household incomes in a city, the length of time between malfunctions of some machine, and major league baseball salaries. The gamma probability distribution, which has two parameters <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>, can model such skewed right distributions. The parameter <span class="math inline">\(\alpha\)</span> is sometimes called the <strong>shape</strong> parameter, <span class="math inline">\(\beta\)</span> is called the <strong>scale</strong> parameter, and its reciprocal <span class="math inline">\(1/\beta\)</span> is called the <strong>rate</strong>.</p>
<p>Here are plots of three different gamma distributions.</p>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-189-1.png" width="591.36" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Suppose <span class="math inline">\(X\)</span> is gamma(<span class="math inline">\(a,b\)</span>).<br />
<strong>In R</strong>, <span class="math inline">\(P(X \leq q)\)</span> is given by <code>pgamma(q,a,1/b)</code></p>
</blockquote>
<blockquote>
<p><strong>Example</strong> Suppose <span class="math inline">\(X\)</span> has a gamma distribution with parameters <span class="math inline">\(\alpha=3\)</span> and <span class="math inline">\(\beta = 4\)</span>. Find <span class="math inline">\(P(4\leq X &lt; 12)\)</span>, which corresponds to the area pictured below.</p>
</blockquote>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-190-1.png" width="591.36" style="display: block; margin: auto;" /></p>
<p>No need for Riemann Sum estimates of this area, we have the built in gamma function.</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="R-continuousRV.html#cb273-1" tabindex="-1"></a>alpha<span class="ot">=</span><span class="dv">3</span>; beta<span class="ot">=</span><span class="dv">4</span></span>
<span id="cb273-2"><a href="R-continuousRV.html#cb273-2" tabindex="-1"></a><span class="fu">pgamma</span>(<span class="dv">12</span>,alpha,<span class="dv">1</span><span class="sc">/</span>beta)<span class="sc">-</span><span class="fu">pgamma</span>(<span class="dv">4</span>,alpha,<span class="dv">1</span><span class="sc">/</span>beta)</span></code></pre></div>
<pre><code>## [1] 0.4965085</code></pre>
<p>Just about a 50% chance that a random value from a gamma(3,4) distribution is between 4 and 12. Ok, so if we gather a random sample of say 1000 values from this distribution, we’d expect somehwere around 500 of them between 4 and 12:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="R-continuousRV.html#cb275-1" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">rgamma</span>(<span class="dv">1000</span>,<span class="dv">3</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>) <span class="co"># random sample of size 1000</span></span>
<span id="cb275-2"><a href="R-continuousRV.html#cb275-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(x<span class="dv">-8</span>)<span class="sc">&lt;</span><span class="dv">4</span>) <span class="co"># values in the sample between 4 and 12</span></span></code></pre></div>
<pre><code>## [1] 518</code></pre>
<p>Well, 518 is mighty close to half of the 1000 values!</p>
<p><strong>Exponential distributions are special gamma distributions.</strong> In particular, if we set <span class="math inline">\(\alpha=1\)</span>, the gamma distribution gamma(1,<span class="math inline">\(\beta\)</span>) is exactly equal to the exponential distribution exp(<span class="math inline">\(\beta\)</span>).</p>
</div>
<div id="chiR" class="section level2 hasAnchor" number="17.5">
<h2><span class="header-section-number">D.5</span> Chi-square Distribution <code>chisq</code><a href="R-continuousRV.html#chiR" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Like the exponential distribution, the chi-square distribution is a special gamma distribution. For a positive integer <span class="math inline">\(\nu\)</span>, the <strong>Chi-square probability distribution with degrees of freedom <span class="math inline">\(\nu\)</span></strong>, denoted <span class="math inline">\(\chi^2(\nu)\)</span>, is the gamma distribution with <span class="math inline">\(\alpha = \nu/2\)</span> and <span class="math inline">\(\beta=2\)</span>.</p>
<p>Here are plots of three different chi-square distributions.</p>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-193-1.png" width="591.36" style="display: block; margin: auto;" /></p>
</div>
<div id="betaR" class="section level2 hasAnchor" number="17.6">
<h2><span class="header-section-number">D.6</span> Beta distribution <code>beta</code><a href="R-continuousRV.html#betaR" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The beta<span class="math inline">\((\alpha,\beta)\)</span> probability distribution provides a way to model random variables whose possible outcomes are all real numbers betweeen 0 and 1. Such distributions are useful for modeling proportions. As with the gamma and normal distributions, this is a 2-parameter family of distributions. Altering the shape parameters <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> gives us, well, different shapes for the density curves.</p>
<p>We note that <strong>beta(1,1) corresponds to the uniform distribution on the interval (0,1)</strong>. Here are plots of density functions for four other beta distributions.</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="R-continuousRV.html#cb277-1" tabindex="-1"></a>t<span class="ot">=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">by=</span>.<span class="dv">01</span>)</span>
<span id="cb277-2"><a href="R-continuousRV.html#cb277-2" tabindex="-1"></a>x1<span class="ot">=</span><span class="fu">dbeta</span>(t,<span class="dv">4</span>,<span class="dv">1</span>)</span>
<span id="cb277-3"><a href="R-continuousRV.html#cb277-3" tabindex="-1"></a>x2<span class="ot">=</span><span class="fu">dbeta</span>(t,<span class="dv">1</span>,<span class="fl">3.5</span>)</span>
<span id="cb277-4"><a href="R-continuousRV.html#cb277-4" tabindex="-1"></a>x3<span class="ot">=</span><span class="fu">dbeta</span>(t,<span class="dv">2</span>,<span class="dv">2</span>)</span>
<span id="cb277-5"><a href="R-continuousRV.html#cb277-5" tabindex="-1"></a>x4<span class="ot">=</span><span class="fu">dbeta</span>(t,<span class="dv">4</span>,<span class="dv">2</span>)</span>
<span id="cb277-6"><a href="R-continuousRV.html#cb277-6" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(t,x1,x2,x3))<span class="sc">+</span></span>
<span id="cb277-7"><a href="R-continuousRV.html#cb277-7" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(t,x1),<span class="at">col=</span><span class="st">&quot;blue&quot;</span>)<span class="sc">+</span></span>
<span id="cb277-8"><a href="R-continuousRV.html#cb277-8" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(t,x2),<span class="at">col=</span><span class="st">&quot;orange&quot;</span>)<span class="sc">+</span></span>
<span id="cb277-9"><a href="R-continuousRV.html#cb277-9" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(t,x3),<span class="at">col=</span><span class="st">&quot;brown&quot;</span>)<span class="sc">+</span></span>
<span id="cb277-10"><a href="R-continuousRV.html#cb277-10" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(t,x4),<span class="at">col=</span><span class="st">&quot;black&quot;</span>)<span class="sc">+</span></span>
<span id="cb277-11"><a href="R-continuousRV.html#cb277-11" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">4</span>))<span class="sc">+</span></span>
<span id="cb277-12"><a href="R-continuousRV.html#cb277-12" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">&quot;x&quot;</span>)<span class="sc">+</span></span>
<span id="cb277-13"><a href="R-continuousRV.html#cb277-13" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="fu">c</span>(.<span class="dv">82</span>,.<span class="dv">2</span>,.<span class="dv">4</span>,.<span class="dv">6</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="fl">2.5</span>,<span class="fl">1.7</span>,<span class="fl">2.2</span>), <span class="at">label =</span> <span class="fu">c</span>(<span class="st">&quot;beta(4,1)&quot;</span>,<span class="st">&quot;beta(1,3.5)&quot;</span>,<span class="st">&quot;beta(2,2)&quot;</span>,<span class="st">&quot;beta(4,2)&quot;</span>),<span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;orange&quot;</span>,<span class="st">&quot;brown&quot;</span>,<span class="st">&quot;black&quot;</span>))</span></code></pre></div>
<p><img src="math340-notes_files/figure-html/unnamed-chunk-194-1.png" width="591.36" style="display: block; margin: auto;" /></p>
<blockquote>
<p><strong>Example</strong> Let <span class="math inline">\(X\)</span> denotes the proportion of sales on a particular website that comes from new customers any given day, and suppose from past experience, <span class="math inline">\(X\)</span> is well-modeled with a beta distribution with shape parameters <span class="math inline">\(\alpha = 1\)</span>, and <span class="math inline">\(\beta=3.5\)</span>. Determine the probability that on any given day, over 1/2 the sales come from new customers.</p>
</blockquote>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="R-continuousRV.html#cb278-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pbeta</span>(<span class="fl">0.5</span>,<span class="dv">1</span>,<span class="fl">3.5</span>)</span></code></pre></div>
<pre><code>## [1] 0.08838835</code></pre>
</div>
<div id="customR" class="section level2 hasAnchor" number="17.7">
<h2><span class="header-section-number">D.7</span> Homemade Continuous Random Variables<a href="R-continuousRV.html#customR" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We may wish to study a continuous random variable <span class="math inline">\(X\)</span> from a given probability density function such as <span class="math inline">\(f(x) = \frac{3}{8}(2-x)^2\)</span> for <span class="math inline">\(0 \leq x \leq 2\)</span>.</p>
<p>In this case, probabilities such as <span class="math inline">\(P(X &gt; 1.2)\)</span> correspond to areas under the density curve, which are calculated by integration, e.g., <span class="math display">\[P(X &gt; 1.2) = \int_{1.2}^2 \frac{3}{8}(2-x)^2~dx.\]</span></p>
<p>If we can find an antiderivative of <span class="math inline">\(f(x)\)</span>, we can find this probability using the fundamental theorem of calculus. If not, we can always estimate the value of the integral with Riemann sums. We do this below.</p>
<div id="input-the-density-function" class="section level3 hasAnchor" number="17.7.1">
<h3><span class="header-section-number">D.7.1</span> Input the density function<a href="R-continuousRV.html#input-the-density-function" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First build the probability density function (pdf) as a function in R.</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="R-continuousRV.html#cb280-1" tabindex="-1"></a>f_pdf <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb280-2"><a href="R-continuousRV.html#cb280-2" tabindex="-1"></a>  <span class="fu">return</span>(<span class="dv">3</span><span class="sc">*</span>(<span class="dv">2</span><span class="sc">-</span>x)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="dv">8</span>)</span>
<span id="cb280-3"><a href="R-continuousRV.html#cb280-3" tabindex="-1"></a>}</span></code></pre></div>
</div>
<div id="visualize-the-density-function" class="section level3 hasAnchor" number="17.7.2">
<h3><span class="header-section-number">D.7.2</span> Visualize the density function<a href="R-continuousRV.html#visualize-the-density-function" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We create a vector of inputs <code>x</code> going from 0 to 2 in small increments (the increment is .01 below), to give us many points over the interval of interest [0,2]. Then we <strong>plot the density curve</strong> by plotting these x values against the function values f(x). (<code>type="l"</code> gives us a <strong>l</strong>ine plot instead of a point plot).</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="R-continuousRV.html#cb281-1" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="at">by=</span>.<span class="dv">01</span>)</span>
<span id="cb281-2"><a href="R-continuousRV.html#cb281-2" tabindex="-1"></a><span class="fu">plot</span>(x,<span class="fu">f_pdf</span>(x),<span class="at">type=</span><span class="st">&quot;l&quot;</span>,</span>
<span id="cb281-3"><a href="R-continuousRV.html#cb281-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;the density function&quot;</span>)</span></code></pre></div>
<p><img src="math340-notes_files/figure-html/plot%20pdf-1.png" width="672" /></p>
</div>
<div id="estimating-integrals-with-riemann-sums" class="section level3 hasAnchor" number="17.7.3">
<h3><span class="header-section-number">D.7.3</span> Estimating Integrals with Riemann Sums<a href="R-continuousRV.html#estimating-integrals-with-riemann-sums" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We know <span class="math inline">\(P(X \geq 1.2)\)</span> corresponds to the area under the density curve between 1.2 and 2. We can estimate areas by computing a Riemann Sum (a sum of many thin rectangle areas approximating the area under the density curve).</p>
<p>Here’s a function for estimating <span class="math inline">\(\int_a^b f(x)~dx\)</span> with a sum of <span class="math inline">\(n\)</span> rectangle areas, generated using the midpoint rule.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="R-continuousRV.html#cb282-1" tabindex="-1"></a>mid.sum<span class="ot">=</span><span class="cf">function</span>(f,a,b,n){</span>
<span id="cb282-2"><a href="R-continuousRV.html#cb282-2" tabindex="-1"></a>  <span class="co">#inputs:</span></span>
<span id="cb282-3"><a href="R-continuousRV.html#cb282-3" tabindex="-1"></a>      <span class="co">#f - function</span></span>
<span id="cb282-4"><a href="R-continuousRV.html#cb282-4" tabindex="-1"></a>      <span class="co">#a, b - lower and upper bounds of interval</span></span>
<span id="cb282-5"><a href="R-continuousRV.html#cb282-5" tabindex="-1"></a>      <span class="co">#n - number of subdivisions</span></span>
<span id="cb282-6"><a href="R-continuousRV.html#cb282-6" tabindex="-1"></a>  <span class="co">#output: The sum of the n rectangle areas whose heights are</span></span>
<span id="cb282-7"><a href="R-continuousRV.html#cb282-7" tabindex="-1"></a>  <span class="co"># determined by the midpoint rule</span></span>
<span id="cb282-8"><a href="R-continuousRV.html#cb282-8" tabindex="-1"></a>  dx<span class="ot">=</span>(b<span class="sc">-</span>a)<span class="sc">/</span>n</span>
<span id="cb282-9"><a href="R-continuousRV.html#cb282-9" tabindex="-1"></a>  ticks<span class="ot">=</span><span class="fu">seq</span>(a<span class="sc">+</span>dx<span class="sc">/</span><span class="dv">2</span>,b,dx)</span>
<span id="cb282-10"><a href="R-continuousRV.html#cb282-10" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">sum</span>(<span class="fu">f</span>(ticks)<span class="sc">*</span>dx))</span>
<span id="cb282-11"><a href="R-continuousRV.html#cb282-11" tabindex="-1"></a>}</span></code></pre></div>
<p>For instance, <code>mid.sum(f_pdf,a=0.4,b=1.2,n=4)</code> computes the area of the 4 rectangles pictured below. We divide the interval [0.4,1.2] into n=4 equal-width subintervals, and build rectangles having height equal to the function height at the midpoint of each of these subintervals.</p>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<pre><code>## Warning in geom_segment(aes(x = 0.59, y = 0, xend = 0.59, yend = f_pdf(0.5)), : All aesthetics have length 1, but the data has 2001 rows.
## ℹ Please consider using `annotate()` or provide this layer with data containing
##   a single row.</code></pre>
<pre><code>## Warning in geom_segment(aes(x = 0.79, y = 0, xend = 0.79, yend = f_pdf(0.7)), : All aesthetics have length 1, but the data has 2001 rows.
## ℹ Please consider using `annotate()` or provide this layer with data containing
##   a single row.</code></pre>
<pre><code>## Warning in geom_segment(aes(x = 0.99, y = 0, xend = 0.99, yend = f_pdf(0.9)), : All aesthetics have length 1, but the data has 2001 rows.
## ℹ Please consider using `annotate()` or provide this layer with data containing
##   a single row.</code></pre>
<pre><code>## Warning in geom_segment(aes(x = 1.2, y = 0, xend = 1.2, yend = f_pdf(1.1)), : All aesthetics have length 1, but the data has 2001 rows.
## ℹ Please consider using `annotate()` or provide this layer with data containing
##   a single row.</code></pre>
<pre><code>## Warning in geom_segment(aes(x = 0.5, y = 0, xend = 0.5, yend = f_pdf(0.5)), : All aesthetics have length 1, but the data has 2001 rows.
## ℹ Please consider using `annotate()` or provide this layer with data containing
##   a single row.</code></pre>
<pre><code>## Warning in geom_segment(aes(x = 0.7, y = 0, xend = 0.7, yend = f_pdf(0.7)), : All aesthetics have length 1, but the data has 2001 rows.
## ℹ Please consider using `annotate()` or provide this layer with data containing
##   a single row.</code></pre>
<pre><code>## Warning in geom_segment(aes(x = 0.9, y = 0, xend = 0.9, yend = f_pdf(0.9)), : All aesthetics have length 1, but the data has 2001 rows.
## ℹ Please consider using `annotate()` or provide this layer with data containing
##   a single row.</code></pre>
<pre><code>## Warning in geom_segment(aes(x = 1.1, y = 0, xend = 1.1, yend = f_pdf(1.1)), : All aesthetics have length 1, but the data has 2001 rows.
## ℹ Please consider using `annotate()` or provide this layer with data containing
##   a single row.</code></pre>
<p><img src="math340-notes_files/figure-html/plot%20sum-1.png" width="384" /></p>
<p>The area of the four rectangles is</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="R-continuousRV.html#cb292-1" tabindex="-1"></a><span class="fu">mid.sum</span>(f_pdf,<span class="at">a=</span>.<span class="dv">4</span>,<span class="at">b=</span><span class="fl">1.2</span>,<span class="at">n=</span><span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.447</code></pre>
</div>
<div id="estimating-probabilities" class="section level3 hasAnchor" number="17.7.4">
<h3><span class="header-section-number">D.7.4</span> Estimating Probabilities<a href="R-continuousRV.html#estimating-probabilities" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>So, getting back to our example, if we want to estimate <span class="math inline">\(P(X &gt; 1.2)\)</span> we can compute a midpoint sum - the more rectangles the better. Let’s start with <span class="math inline">\(n = 100\)</span>:</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="R-continuousRV.html#cb294-1" tabindex="-1"></a><span class="fu">mid.sum</span>(f_pdf,<span class="fl">1.2</span>,<span class="dv">2</span>,<span class="dv">100</span>)</span></code></pre></div>
<pre><code>## [1] 0.0639984</code></pre>
<p>What if we use <span class="math inline">\(n = 1000\)</span> rectangles?</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="R-continuousRV.html#cb296-1" tabindex="-1"></a><span class="fu">mid.sum</span>(f_pdf,<span class="fl">1.2</span>,<span class="dv">2</span>,<span class="dv">1000</span>)</span></code></pre></div>
<pre><code>## [1] 0.06399998</code></pre>
<p>It seems as if our estimate hasn’t changed much by going from 100 to 1000 subintervals, for this density function.</p>
<p>To estimate <span class="math inline">\(P(0.5 &lt; X &lt; 1.1)\)</span> we can evaluate</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="R-continuousRV.html#cb298-1" tabindex="-1"></a><span class="fu">mid.sum</span>(f_pdf,<span class="fl">0.5</span>,<span class="fl">1.1</span>,<span class="dv">100</span>)</span></code></pre></div>
<pre><code>## [1] 0.3307493</code></pre>
</div>
<div id="the-distribution-function-fx" class="section level3 hasAnchor" number="17.7.5">
<h3><span class="header-section-number">D.7.5</span> The distribution function <span class="math inline">\(F(X)\)</span><a href="R-continuousRV.html#the-distribution-function-fx" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall, <span class="math inline">\(F(x)\)</span> gives cumulative probability. In particular, <span class="math inline">\(F(x) = P(X \leq x)\)</span>.</p>
<p>Consider again the random variable <span class="math inline">\(X\)</span> with pdf <span class="math inline">\(f(x) = (3/8)(2-x)^2\)</span> for <span class="math inline">\(0 &lt; x &lt; 2\)</span>.</p>
<p>For any value of <span class="math inline">\(b\)</span> between 0 and 2, <span class="math display">\[F(b) = \int_0^b f(x)~dx,\]</span>
which we can numerically approximate with</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="R-continuousRV.html#cb300-1" tabindex="-1"></a>F_example <span class="ot">&lt;-</span> <span class="cf">function</span>(b){</span>
<span id="cb300-2"><a href="R-continuousRV.html#cb300-2" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">mid.sum</span>(f_pdf,<span class="dv">0</span>,b,<span class="dv">100</span>))</span>
<span id="cb300-3"><a href="R-continuousRV.html#cb300-3" tabindex="-1"></a>}</span></code></pre></div>
<p>Then we can sketch the graph of the distribution function, for inputs between 0 and 2</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="R-continuousRV.html#cb301-1" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="at">by=</span>.<span class="dv">01</span>)</span>
<span id="cb301-2"><a href="R-continuousRV.html#cb301-2" tabindex="-1"></a>y<span class="ot">=</span><span class="fu">c</span>()</span>
<span id="cb301-3"><a href="R-continuousRV.html#cb301-3" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(x)){</span>
<span id="cb301-4"><a href="R-continuousRV.html#cb301-4" tabindex="-1"></a>  y<span class="ot">=</span><span class="fu">c</span>(y,<span class="fu">F_example</span>(x[i]))</span>
<span id="cb301-5"><a href="R-continuousRV.html#cb301-5" tabindex="-1"></a>}</span>
<span id="cb301-6"><a href="R-continuousRV.html#cb301-6" tabindex="-1"></a><span class="fu">plot</span>(x,y,<span class="at">type=</span><span class="st">&quot;l&quot;</span>,</span>
<span id="cb301-7"><a href="R-continuousRV.html#cb301-7" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;the distribution function&quot;</span>)</span></code></pre></div>
<p><img src="math340-notes_files/figure-html/plot%20distn%20fcn-1.png" width="672" /></p>
</div>
<div id="estimating-moments" class="section level3 hasAnchor" number="17.7.6">
<h3><span class="header-section-number">D.7.6</span> Estimating Moments<a href="R-continuousRV.html#estimating-moments" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall, <span class="math inline">\(E(X^n)\)</span> is called the <em><span class="math inline">\(n\)</span>th moment about 0</em> of the distribution. The first moment is the expected value <span class="math inline">\(E(X)\)</span>, and the 2nd and 1st together determine the variance: <span class="math inline">\(V(X) = E(X^2)-E(X)^2.\)</span></p>
<p>For a continuous random variable <span class="math inline">\(X\)</span> with pdf <span class="math inline">\(f(x)\)</span>, <span class="math display">\[E(X^n) = \int_{-\infty}^\infty x^n \cdot f(x).\]</span></p>
<p>In R we can numerically estimate these integrals with the <code>mid.sum()</code> function defined above, applied to the integrand <span class="math inline">\(x^n\cdot f(X)\)</span>.</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="R-continuousRV.html#cb302-1" tabindex="-1"></a>moment.integrand<span class="ot">&lt;-</span><span class="cf">function</span>(f,n){</span>
<span id="cb302-2"><a href="R-continuousRV.html#cb302-2" tabindex="-1"></a>  <span class="co">#inputs:</span></span>
<span id="cb302-3"><a href="R-continuousRV.html#cb302-3" tabindex="-1"></a>      <span class="co"># f - a previously defined pdf</span></span>
<span id="cb302-4"><a href="R-continuousRV.html#cb302-4" tabindex="-1"></a>      <span class="co"># n - an integer</span></span>
<span id="cb302-5"><a href="R-continuousRV.html#cb302-5" tabindex="-1"></a>  <span class="co">#output: the integrand function for evaluating E(X^n)</span></span>
<span id="cb302-6"><a href="R-continuousRV.html#cb302-6" tabindex="-1"></a>  <span class="fu">return</span>(<span class="cf">function</span>(x){<span class="fu">return</span>(x<span class="sc">^</span>n<span class="sc">*</span><span class="fu">f</span>(x))})</span>
<span id="cb302-7"><a href="R-continuousRV.html#cb302-7" tabindex="-1"></a>}</span></code></pre></div>
</div>
<div id="expected-value-1" class="section level3 hasAnchor" number="17.7.7">
<h3><span class="header-section-number">D.7.7</span> Expected Value<a href="R-continuousRV.html#expected-value-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For a continuous random variable <span class="math inline">\(X\)</span>, <span class="math display">\[E(X)=\int_{-\infty}^{\infty} x \cdot f(x)~dx.\]</span></p>
<p>To estimate this integral, we plug the first moment integrand <span class="math inline">\(x \cdot f(x)\)</span> into our Riemann sum function.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="R-continuousRV.html#cb303-1" tabindex="-1"></a>mu<span class="ot">=</span><span class="fu">mid.sum</span>(<span class="fu">moment.integrand</span>(f_pdf,<span class="dv">1</span>),<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">100</span>)</span>
<span id="cb303-2"><a href="R-continuousRV.html#cb303-2" tabindex="-1"></a>mu</span></code></pre></div>
<pre><code>## [1] 0.500025</code></pre>
<p>Note: The actual expected value is</p>
<p><span class="math display">\[\int_0^2 x \cdot (3/8)(2-x)^2~dx = 0.5.\]</span></p>
<p>We estimate the <strong>variance</strong> knowing that <span class="math inline">\(V(X) = E(X^2)-E(X)^2.\)</span></p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="R-continuousRV.html#cb305-1" tabindex="-1"></a>EX2<span class="ot">=</span><span class="fu">mid.sum</span>(<span class="fu">moment.integrand</span>(f_pdf,<span class="dv">2</span>),<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">100</span>)</span>
<span id="cb305-2"><a href="R-continuousRV.html#cb305-2" tabindex="-1"></a>EX2</span></code></pre></div>
<pre><code>## [1] 0.4</code></pre>
<p>So the variance of <span class="math inline">\(X\)</span> is</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="R-continuousRV.html#cb307-1" tabindex="-1"></a>EX2<span class="sc">-</span>mu<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.149975</code></pre>
<p>Note: The actual value of <span class="math inline">\(E(X^2)\)</span> is <span class="math display">\[\int_0^2 x^2 \cdot (3/8)(2-x)^2~dx = 0.4,\]</span>
so <span class="math inline">\(V(X) = 0.4 - (0.5)^2 = 0.15.\)</span></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="R-discreteRV.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/mphitchman/math340/edit/main/source/R04-continuous-RV.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["math340-notes.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
